### PR TITLE
Atomiswave Box Art

### PR DESCRIPTION
**Pull request by mrrichard999**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Thumbnails must not be named that way, see existing names in https://github.com/libretro-thumbnails/Atomiswave/tree/master/Named_Boxarts

Since it's an arcade system, i'd guess you are supposed to use manual scan with a dat file from MAME when creating an aw playlist, hence why the thumbnails must match the names from the dat file.

**Comment by mrrichard999** [comment]
I was going off the list here on the missing thumbnail section - libretro-thumbnails-check/Atomiswave.txt at master · RobLoach/libretro-thumbnails-check

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
libretro-thumbnails-check/Atomiswave.txt at master · RobLoach/libretro-t...

Checks consistency of libretro-thumbnails. Contribute to RobLoach/libretro-thumbnails-check development by creat...
 |

 |

 |




    On Tuesday, April 4, 2023 at 05:16:14 AM EDT, barbudreadmon ***@***.***> wrote:  
 
 


Thumbnails must not be named that way, see existing names in https://github.com/libretro-thumbnails/Atomiswave/tree/master/Named_Boxarts

**Comment by RobLoach** [comment]
Just updated the DB to use the actual game names rather than the IDs. Good catch!

**Comment by mrrichard999** [comment]
Awesome! Back to work :D

    On Tuesday, April 4, 2023 at 02:55:20 PM EDT, Rob Loach ***@***.***> wrote:  
 
 


Just updated the DB to use the actual game names rather than the IDs. Good catch!

**Pull request closed without merging**
